const AdminActionTypes = {
  TOGGLE_BC_MODAL: "TOGGLE_BC_MODAL",
  OPEN_BC_MODAL_HANDLER: "OPEN_BC_MODAL_HANDLER",
  CLOSE_BC_MODAL_HANDLER: "CLOSE_BC_MODAL_HANDLER",
  OPEN_RC_MODAL_HANDLER: "OPEN_RC_MODAL_HANDLER",
  CLOSE_RC_MODAL_HANDLER: "CLOSE_RC_MODAL_HANDLER",
};

export default AdminActionTypes;
